In [1]:
pip install numpy

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     -------------------- ------------------- 30.7/60.8 kB 1.4 MB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 816.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.9 MB 2.6 MB/s eta 0:00:06
    --------------------------------------- 0.3/12.9 MB 3.5 MB/s eta 0:00:04
   - -------------------------------------- 0.6/12.9 MB 4.9 MB/s eta 0:00:03
   --- ------------------------------------ 1.2/12.9 MB 6.7 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/12.9 MB 7.4 MB/s eta 0:00:02
   ------ --------------------------------- 2.2/12.9 MB 8.0 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.9 MB 8.3 MB/s eta 0:00:02
   --------- ------------------------------ 3.1/12.9 MB 8.6 MB/s eta 0:00:02
   ----------- ---------------------------- 3.6/12.9 MB 8.9 MB/s eta 0:00:02
   --

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [7]:
arr = np.random.randint(1,50,size=(10))
arr

array([20, 24, 38, 41, 18, 14,  7, 13,  9, 25], dtype=int32)

In [8]:
np.mean(arr)

np.float64(20.9)

In [9]:
arr1 = np.random.randint(1,10,size=(3,3))
arr1

array([[4, 1, 6],
       [8, 9, 8],
       [5, 6, 8]], dtype=int32)

In [10]:
arr2 = np.random.randint(1,10,size=(3,3))
arr2

array([[4, 6, 1],
       [1, 3, 4],
       [8, 3, 4]], dtype=int32)

In [11]:
arr3 = arr1 + arr2
arr3

array([[ 8,  7,  7],
       [ 9, 12, 12],
       [13,  9, 12]], dtype=int32)

In [12]:
np.mean(arr3)

np.float64(9.88888888888889)

In [14]:
arr = np.random.randint(1,100,size=(20))
arr
condition = arr > 50
filtered_arr = arr[condition]
filtered_arr

array([99, 77, 52, 58, 80, 98, 87, 93, 67, 63, 90], dtype=int32)